spring:
  application:
    name: forex-service
  jpa:
    show-sql: true
  datasource:
    username: root
    password: leimuhua
    url: jdbc:mysql://localhost:3306/forex?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
